### ISSUE TITLE
Is this a pure linear gradient that does not take into account Brightness and Gamma Values?

### ISSUE THREAD

**Issue by lynniemagoo** [Adrinlol/javascript-color-gradient#22]
Nice job on the code.  

When I run the application, I see not a good transition from red to yellow to green but rather to brown in the middle.  

I've run across this article and I was planning on implementing in JavaScript as well.   The framework you have here is one that is quite nice and I was curious as to whether thoughts outlined here had ever come up?

https://stackoverflow.com/questions/22607043/color-gradient-algorithm/39924008#39924008

**Comment by Adrinlol** [comment]
Hey @lynniemagoo, sorry for the delay, it's been a while since I've checked GitHub.

This project is just a snippet I've decided to open-source when working on a different task (for specific hex values). Unfortunately, I don't have the time to maintain this project now.
