### ISSUE TITLE
Missing zeros in color codes

### ISSUE THREAD

**Issue by ruester** [Adrinlol/javascript-color-gradient#3]
Used version: 1.2.2 (the [npm site](https://www.npmjs.com/package/javascript-color-gradient) states that version 1.2.3 should be released (?), but I could not found it here on GitHub)

The following example generates invalid color codes:

```javascript
colorGradient.setGradient("#ff0000", "#00ff00");
colorGradient.setMidpoint(8);
console.log(colorGradient.getArray());
```

> ["#df200", "#bf400", "#9f600", "#80800", "#609f0", "#40bf0", "#20df0", "#0ff0"]

The colors need a trailing `0` and the last color needs a trailing and leading `0`.

**Comment by Saspect-IO** [comment]
This yields from any decimal value below 16 (0-15) generating a hex with 1 char when using str.toString(16) conversion:
Adding leading "0" for these values resolves the issue.

Tests:
         for (let i = 0; i < 17; i++) {
            const decimal = i;
            console.log(`[decimal]: ${decimal}, [hex]:${decimal.toString(16)}`);
        }
        /*
        result below:

        [decimal]: 0, [hex]:0
        [decimal]: 1, [hex]:1
        [decimal]: 2, [hex]:2
        [decimal]: 3, [hex]:3
        [decimal]: 4, [hex]:4
        [decimal]: 5, [hex]:5
        [decimal]: 6, [hex]:6
        [decimal]: 7, [hex]:7
        [decimal]: 8, [hex]:8
        [decimal]: 9, [hex]:9
        [decimal]: 10, [hex]:a
        [decimal]: 11, [hex]:b
        [decimal]: 12, [hex]:c
        [decimal]: 13, [hex]:d
        [decimal]: 14, [hex]:e
        [decimal]: 15, [hex]:f
        [decimal]: 16, [hex]:10
        
        */
