### ISSUE TITLE
"dist" directory missing in 1.2.3 release 

### ISSUE THREAD

**Issue by Saspect-IO** [Adrinlol/javascript-color-gradient#4]
"dist" directory missing in  "v1.2.3" release  : resulting in error not able to resolve module path.

![image](https://user-images.githubusercontent.com/29488727/98200838-734dc300-1efc-11eb-9b45-01a4c82fdd16.png)

**Comment by Adrinlol** [comment]
Hi Saspect-IO,

Thanks for reporting this issue. I'll have to get back to it later on, meanwhile, please downgrade the javascript-color-gradient to v.1.2.2 to fix this issue.

`npm install javascript-color-gradient@1.2.2 `

or 

`yarn add javascript-color-gradient@1.2.2`

**Comment by Adrinlol** [comment]
Resolved!
